### ISSUE TITLE
Python class / magic functions

### ISSUE THREAD

**Issue by mpsido** [raynardj/python4ml#11]
Hello I am preparing a course about object oriented programming, classes and magic functions

**Comment by raynardj** [comment]
will there be generator and decorators? @mpsido

**Comment by mpsido** [comment]
not on that lesson, but I think Sanada1615 can help write something about generators. I sounded pretty expert on generators last time I talked to him

**Comment by raynardj** [comment]
@mpsido  That would be wonderful
