### ISSUE TITLE
course about decorator & generator

### ISSUE THREAD

**Issue by raynardj** [raynardj/python4ml#14]
@sanada1615 @bartgras @mpsido  we need jupyter notebook go through of python decorator and generator. 

Cleaned rip off from good blogs or other sources will totally be alright.

* [ ] Course about python decorator

* [ ] Course about python generator

For the continuity of the course, please make sure the jupyter kernel is on anaconda3

**Comment by ctivanovich** [comment]
I'm happy to do the one on generators, if no one has started it. Decorators, I only learned about recently.

**Comment by mpsido** [comment]
I was about to suggest the same. but if believe it brings more value that do the matplotlib first.
we can leave the generator tutorial for you.

i can take decorators

**Comment by ctivanovich** [comment]
Okay. I'm actually going to throw in comprehensions as well, since the syntax is related to that used in the generators discussion.

**Comment by mpsido** [comment]
adding decorators course in commit
[d73aadeddeb4e1453cbe9aac03876f70a50d9f19](https://github.com/raynardj/python4ml/commit/d73aadeddeb4e1453cbe9aac03876f70a50d9f19)

**Comment by mpsido** [comment]
The course about generatos was added by @ctivanovich in this [commit](https://github.com/raynardj/python4ml/commit/16dfbbfc4aaf6ca3453843732408dfb6cd6d3222).

Closing issue
